# Generated by Django 5.2.10 on 2026-01-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_canarytrap_canarytraptrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='storage_limit',
            field=models.BigIntegerField(default=20971520, help_text='Maximum storage allowed in bytes (default: 20MB for Free Tier)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='storage_used',
            field=models.BigIntegerField(default=0, help_text='Current storage used in bytes (auto-calculated from uploaded files)'),
        ),
    ]
