# Generated by Django 5.2 on 2026-03-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_security_pin_to_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duresssession',
            name='token_key',
            field=models.CharField(help_text='SHA-256 hash of the auth token', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='multitoken',
            name='key',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
