# Generated by Django 5.2 on 2026-03-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_secure_token_hash_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrecord',
            name='username_attempted',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the profile was moved to trash (null = not deleted)', null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this session is active'),
        ),
    ]
